version: '3'
services:
  db:
    build: .
    ports:
      - 5433:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      # POSTGRES_USER: admin
      # POSTGRES_PASSWORD: admin
    volumes:
      - ./:/work
    working_dir: /work